version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: maf
      POSTGRES_PASSWORD: maf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maf"]
      interval: 5s
      timeout: 5s
      retries: 5
  auth-service:
    build: ./services/auth-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: maf
      SPRING_DATASOURCE_PASSWORD: maf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: auth
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres

  user-service:
    build: ./services/user-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: maf
      SPRING_DATASOURCE_PASSWORD: maf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "user"
    depends_on:
      - postgres


  product-service:
    build: ./services/product-service
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productdb
      SPRING_DATASOURCE_USERNAME: maf
      SPRING_DATASOURCE_PASSWORD: maf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: product
    depends_on:
      - postgres

  order-service:
    build: ./services/order-service
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: maf
      SPRING_DATASOURCE_PASSWORD: maf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "order"
    depends_on:
      - postgres

  cart-service:
    build: ./services/cart-service
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cartdb
      SPRING_DATASOURCE_USERNAME: maf
      SPRING_DATASOURCE_PASSWORD: maf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: cart
    depends_on:
      - postgres

  messaging-service:
    build: ./services/messaging-service
    ports:
      - "8086:8086"
    environment:
      SERVER_PORT: 8086
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/messagingdb
      SPRING_DATASOURCE_USERNAME: maf
      SPRING_DATASOURCE_PASSWORD: maf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: messaging
    depends_on:
      - postgres

  notification-service:
    build: ./services/notification-service
    ports:
      - "8087:8087"
    environment:
      SERVER_PORT: 8087
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notificationdb
      SPRING_DATASOURCE_USERNAME: maf
      SPRING_DATASOURCE_PASSWORD: maf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: notification
    depends_on:
      - postgres

  payment-service:
    build: ./services/payment-service
    ports:
      - "8088:8088"
    environment:
      SERVER_PORT: 8088
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: maf
      SPRING_DATASOURCE_PASSWORD: maf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: payment
    depends_on:
      - postgres

volumes:
  pgdata: