server:
  port: 8081  # змінити під кожен сервіс

spring:
  datasource:
    url: ${CART_DB_URL}
    username: ${CART_DB_USERNAME}
    password: ${CART_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true