server:
  port: 8081

spring:
  datasource:
    url: ${MESSAGING_DB_URL}
    username: ${MESSAGING_DB_USERNAME}
    password: ${MESSAGING_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true