server:
  port: 8081  # змінити під кожен сервіс

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/messagingdb  # змінити під кожен сервіс
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true