server:
  port: 8082

spring:
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health, info
